/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const ContentType = IDL.Variant({
  'video' : IDL.Null,
  'interview' : IDL.Null,
  'article' : IDL.Null,
  'featureStory' : IDL.Null,
});
export const Category = IDL.Variant({
  'newsAndViews' : IDL.Null,
  'marketTrends' : IDL.Null,
  'interviews' : IDL.Null,
  'startupsAndFunding' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Text,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'contentType' : ContentType,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'publishedAt' : IDL.Opt(IDL.Int),
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'category' : Category,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const NewsletterSubscription = IDL.Record({
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'archiveArticle' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([Article], [], []),
  'deleteArticle' : IDL.Func([IDL.Text], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscription)],
      ['query'],
    ),
  'getArticleById' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'getArticlesByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func([Category], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func([IDL.Text], [], []),
  'removeAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticlesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateArticle' : IDL.Func([IDL.Text, Article], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ContentType = IDL.Variant({
    'video' : IDL.Null,
    'interview' : IDL.Null,
    'article' : IDL.Null,
    'featureStory' : IDL.Null,
  });
  const Category = IDL.Variant({
    'newsAndViews' : IDL.Null,
    'marketTrends' : IDL.Null,
    'interviews' : IDL.Null,
    'startupsAndFunding' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Text,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'contentType' : ContentType,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'publishedAt' : IDL.Opt(IDL.Int),
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'category' : Category,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const NewsletterSubscription = IDL.Record({
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'archiveArticle' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([Article], [], []),
    'deleteArticle' : IDL.Func([IDL.Text], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscription)],
        ['query'],
      ),
    'getArticleById' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'getArticlesByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func([IDL.Text], [], []),
    'removeAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticlesByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateArticle' : IDL.Func([IDL.Text, Article], [], []),
  });
};

export const init = ({ IDL }) => { return []; };