/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : string,
  'status' : ArticleStatus,
  'title' : string,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'contentType' : ContentType,
  'body' : string,
  'slug' : string,
  'publishedAt' : [] | [bigint],
  'author' : string,
  'summary' : string,
  'category' : Category,
  'videoUrl' : [] | [string],
}
export type ArticleStatus = { 'published' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export type Category = { 'connectedDevices' : null } |
  { 'marketTrends' : null } |
  { 'interviews' : null } |
  { 'aiAndData' : null } |
  { 'startupsAndFunding' : null } |
  { 'veterinaryTech' : null } |
  { 'videos' : null };
export type ContentType = { 'video' : null } |
  { 'interview' : null } |
  { 'article' : null } |
  { 'featureStory' : null };
export interface UserProfile { 'bio' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Assign the #admin role to a principal.
   * / AccessControl.assignRole already enforces that only admins can call this.
   */
  'addAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'archiveArticle' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[Article], undefined>,
  'deleteArticle' : ActorMethod<[string], undefined>,
  /**
   * / Returns ALL articles (including drafts/archived) — admin only.
   */
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  /**
   * / Returns a single article by id.
   * / Admins can see any status; others only see published.
   */
  'getArticleById' : ActorMethod<[string], [] | [Article]>,
  /**
   * / Returns published articles by a given author — public.
   */
  'getArticlesByAuthor' : ActorMethod<[string], Array<Article>>,
  /**
   * / Returns published articles in a given category — public.
   */
  'getArticlesByCategory' : ActorMethod<[Category], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns featured published articles — public.
   */
  'getFeaturedArticles' : ActorMethod<[], Array<Article>>,
  /**
   * / Returns only published articles — public.
   */
  'getPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishArticle' : ActorMethod<[string], undefined>,
  /**
   * / Demote a principal back to #guest.
   * / AccessControl.assignRole already enforces that only admins can call this.
   */
  'removeAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Full-text search on title among published articles — public.
   */
  'searchArticlesByTitle' : ActorMethod<[string], Array<Article>>,
  'updateArticle' : ActorMethod<[string, Article], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];